//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1024x1024_roble_oscuro {
            get {
                object obj = ResourceManager.GetObject("1024x1024-roble-oscuro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Arfil_Blanco {
            get {
                object obj = ResourceManager.GetObject("Arfil Blanco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Arfil_Blanco1 {
            get {
                object obj = ResourceManager.GetObject("Arfil Blanco1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Arfil_negro_2 {
            get {
                object obj = ResourceManager.GetObject("Arfil negro 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caballo_Blanco {
            get {
                object obj = ResourceManager.GetObject("Caballo Blanco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caballo_negro {
            get {
                object obj = ResourceManager.GetObject("Caballo negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chocolate {
            get {
                object obj = ResourceManager.GetObject("Chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fondo_de_madera_apple_3913 {
            get {
                object obj = ResourceManager.GetObject("fondo-de-madera-apple-3913", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fondo_madera_marron {
            get {
                object obj = ResourceManager.GetObject("fondo-madera-marron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gris_oscuro {
            get {
                object obj = ResourceManager.GetObject("gris oscuro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H1555_ST15 {
            get {
                object obj = ResourceManager.GetObject("H1555_ST15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_0557 {
            get {
                object obj = ResourceManager.GetObject("IMG_0557", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Juntas_rayas_textura_de_fondo_de_madera_900x1440 {
            get {
                object obj = ResourceManager.GetObject("Juntas-rayas-textura-de-fondo-de-madera-900x1440", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MADERA {
            get {
                object obj = ResourceManager.GetObject("MADERA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Madera_Clara {
            get {
                object obj = ResourceManager.GetObject("Madera Clara", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Madera_fondo_oscuro {
            get {
                object obj = ResourceManager.GetObject("Madera fondo oscuro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Madera_Oscura {
            get {
                object obj = ResourceManager.GetObject("Madera Oscura", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MARMOL {
            get {
                object obj = ResourceManager.GetObject("MARMOL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peon_Blanco {
            get {
                object obj = ResourceManager.GetObject("Peon Blanco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peon_Blanco1 {
            get {
                object obj = ResourceManager.GetObject("Peon Blanco1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peon_Negro {
            get {
                object obj = ResourceManager.GetObject("Peon Negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peon_negro_2__1_ {
            get {
                object obj = ResourceManager.GetObject("peon_negro_2 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peon_negro_2__1_1 {
            get {
                object obj = ResourceManager.GetObject("peon_negro_2 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peon_negro_2__1_2 {
            get {
                object obj = ResourceManager.GetObject("peon_negro_2 (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peon_negro_2__1_3 {
            get {
                object obj = ResourceManager.GetObject("peon_negro_2 (1)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peon_Negro1 {
            get {
                object obj = ResourceManager.GetObject("Peon Negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reina_Blanca {
            get {
                object obj = ResourceManager.GetObject("Reina Blanca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reina_Negra {
            get {
                object obj = ResourceManager.GetObject("Reina Negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rey_Blanco {
            get {
                object obj = ResourceManager.GetObject("Rey Blanco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rey_negro {
            get {
                object obj = ResourceManager.GetObject("Rey negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sin_título_2 {
            get {
                object obj = ResourceManager.GetObject("Sin título-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sin_título_21 {
            get {
                object obj = ResourceManager.GetObject("Sin título-21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Textura_de_madera_911413 {
            get {
                object obj = ResourceManager.GetObject("Textura de madera-911413", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textura_madera_2_clara_base {
            get {
                object obj = ResourceManager.GetObject("textura madera 2 clara base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textura_madera_2_clara_base1 {
            get {
                object obj = ResourceManager.GetObject("textura madera 2 clara base1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap torre {
            get {
                object obj = ResourceManager.GetObject("torre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Torre_Blanca {
            get {
                object obj = ResourceManager.GetObject("Torre Blanca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Torre_negra {
            get {
                object obj = ResourceManager.GetObject("Torre negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
